name: Lint workflow

on:
  pull-request:
  branches:
  -master

  jobs:
  test:
  runs-on: ubunty-latest
  steps:
  -name: Checkout code
  uses: actions/checkout@v1
  -name: Use Node.js 12.x
  uses: actions/setup-node@v1
  with:
  node-version: 12.x
  -name: install deps
  run: npm install
  -name: Run lint
  run: npm run eslint